### PR TITLE
Added MS5803 Pressure/Temperature sensor

### PR DESCRIPTION
**Pull request by ryanneve**
I2C library for Measurement Specialties MS5803 family of Pressure/Temperature sensors.

### CODE REVIEW

**Comment by eadf** [comment]
I just took a quick look at the code and it looks good. Just noticed two things:  

- It looks like it is `calcMeasurements()` that does the heavy lifting, getting data from the device and converting it, while the 'getters' actually just returns buffered and prepared data. It would be nice if this was documented in the`calcMeasurements()`description.

- `keywords.txt` contains some (copy&paste?) reference to LiquidCrystal_I2C.

**Comment by ryanneve** [comment]
I made some changes and pushed the code. Do I need a new pull request?

**Comment by eadf** [comment]
Nice!

Hm, usually it is enough to push your local changes back to the (github) repository you made the pull request from. Are you sure you did push to remote? Cause when I look at your repository I can only see the original commit. 

Anyhow, you won't be needing a new pull request.

P.S. you probably should update your github repository, it is 169 commits behind jrowberg:master.

**Comment by ryanneve** [comment]
ok, how about now? Did I fix it?

**Comment by eadf** [comment]
Yes you did. GJ.
I don't own a MS5803 so I can't test it, but I take it that you tested your driver with the latest i2cdevlib.
Lets give @jrowberg a few days to provide his feedback.

**Comment by jrowberg** [comment]
This looks fine to me. Thanks for your contributions and review, both of you!

**Pull request merged**
