### PR TITLE
Don't do anything special for Teensy, just use regular Arduino Wire lib

### PR DESCRIPTION
**Pull request by PaulStoffregen**
This fixes compatibility problems reported by multiple people here:

https://forum.pjrc.com/threads/32971-Teensy-MPU6050-Library-Conflicts

### CODE REVIEW

**Comment by udawat** [comment]
Thanks Paul for this simple fix.
@jrowberg I have merged this fix as it solves basic I2C communication issue with the Teensy.

**Comment by jrowberg** [comment]
Thanks, both of you!

**Comment by PaulStoffregen** [comment]
I've got another batch of small updates... waiting for a customer to confirm they solve his problems before sending the pull request.

**Comment by jrowberg** [comment]
@PaulStoffregen Much appreciated. I originally put the core library, initial device classes, and website together five years ago, and have a list as long as my arm of things that I would like to improve or add. I've been relying on the community due other pressing priorities. Any and all input from others is welcome.

**Comment by PaulStoffregen** [comment]
I've got one more round of minor improvements, mainly lots of little places that were meant to run 32 bit float (which is the only type of floating point on AVR) but for various reasons they end up forcing 64 bit float on many modern boards which support both 32 & 64 bit floats.

Long term (and in a dream world where many work more hours exist in every day), I believe Arduino users really need a higher level API for motion sensors, where mundane details like scaling factors and synchronizing to sensor sample rates are done automatically and consistently, and where filter/fusion algorithms and post-processing libs can be used without requiring lots of glue code in the user's sketch.

**Pull request merged**
