### PR TITLE
AD7746 example

### PR DESCRIPTION
**Pull request by acseckin**
I need your library to use ad7746. please add an example for ad7746.

### CODE REVIEW

**Comment by Maclain272** [comment]
I AM IN SEARCHING FOR MPU 6050 6AXIS_MotionApps20.h

**Comment by Maclain272** [comment]
> Hi! humans .
allow get this library include to Arduino project robot

**Comment by Maclain27** [comment]
> mention it in earth code for human.

**Comment by jrowberg** [comment]
Closing pointless PR for cleanup.

**Pull request closed without merging**
