### PR TITLE
Added Extra function for AD7745

### PR DESCRIPTION
**Pull request by OptifySudarshanPatil**

### CODE REVIEW

**Comment by OptifySudarshanPatil** [comment]
Sample use of additional function as follows.
`AD7746_sensor.writeAD7745Register(0x00, 0x02);`

**Comment by jrowberg** [comment]
This is a clean change, but I'm not sure why it's necessary. It's just a passthrough to the base I2Cdev call without anything specific to the AD774x ICs, other than taking advantage of the device class's predefined address byte. It's fine as a project-specific convenience function, but I don't think it makes sense to incorporate as an addition to the core library code.

**Comment by OptifySudarshanPatil** [comment]
This function was added to incorporate/feed an array of fixed settings to AD774x  in one go without calling individual function.
This helps while reconnection AD774x in i2c block mode recovery (hot reconnect attempt).

**Comment by jrowberg** [comment]
I see. That makes sense, but as written it's still more specific than I think it should be for generic device library code. I like the idea of providing simple passthrough methods for quick register modification, but in that case it should more ideally be something like `writeRegister(...)` instead of `writeAD7745Register(...)`. There isn't any real reason I can see why it helps to have the device name (especially one that's slightly different from the rest of the device library) right in the method name.

**Comment by OptifySudarshanPatil** [comment]
Correct!
Function should have generic name instead device name.
This function is simple wire write wrapper.

**Pull request merged**
