### PR TITLE
updated L3G4200D::getAngularVelocityN() functions

### PR DESCRIPTION
**Pull request by diegob94**
I was trying to use this library but the raw values from the gyro where always positive, so I check the code and I found two mayor problems, first this call "if (getEndianMode() == L3G4200D_BIG_ENDIAN) {" re-use the buffer so the code below (where the function actually returns gyro values) produces values that are obiusly wrong, and the second thing I notice was that the I2Cdev::readBytes call just return the L3G4200D_RA_OUT_N_L register twice (L3G4200D_RA_OUT_N_H is was not being readed), so just half of the data was being received, so I try to fix it and it works, so if you could take a look and make something better it would be greate for people who are trying to use this gyro with this library.

### CODE REVIEW

**Comment by natecostello** [comment]
I think you are partially right:  The code should read "if (getEndianMode()==L3G4200D_LITTLE_ENDIAN)..."  With that change the bit shifting logic works out.  As for the other issue you raise, readBytes when given a length of 2 will read two bytes starting at the given register address and incrementing up by one, so the function should read both the L and H bytes as written.
Not sure about the always positive result you were getting, but it could be due to the 2s complement format.

**Comment by natecostello** [comment]
After messing around, you are totally right.  On this device, and the L3GD20H..and probably other ST devices, to read sequential addresses (e.g. x low and x high) you have to set the register MSB to '1'.  Otherwise it just re-reads the same register twice.  Based on that implementation by ST, the plumbing for this library is broken when it comes to ST devices.  It can by patched by using "REG_ADDRESS | 0x80" instead of REG_ADDRESS whenever readBytes is called in a function.  That feels a little "hacky" though.

**Comment by diegob94** [comment]
yeah haven't noticed it from the datasheet: 
"... an 8-bit sub-address is transmitted. The 7 LSb represent the actual register address while the MSB enables address auto-increment. If the MSb of the SUB field is 1, the SUB (register address) is automatically incremented to allow multiple data read/write."
its just the way it's implemented and I don't see any other way of fixing it, I mean you can read the registers by separate (like I did) or set the address MSB to 1, which can be done in the call to readBytes or change all the macros for the addresses in the header file to have the MSB set, but thats just clumsy, using "REG_ADDRESS | 0x80" like you said is a good solution.

**Comment by natecostello** [comment]
I found another problem.  In the getAngularVelocity_() functions, it reads they output registers for the angular velocity data, and then calls getEndianMode() to determine how to parse the angular velocity data.  However, when it does this, it overwrites the least significant byte of the angular velocity data (in buffer) to be either 00000000 00000001 based on what getEndianMode returns.  That one took a while to trackdown.

**Pull request merged**
