### PR TITLE
I2Cdev library added for a Raspberry Pi, with a few examples

### PR DESCRIPTION
**Pull request by hamish2014**
Hi,

Thanks for the i2cdevlib.
Here are my additions for a Raspberry Pi, should you wish to use them.

Regards,

### CODE REVIEW

**Comment by jrowberg** [comment]
Hi @hamish2014,

This looks like a great addition! Can you clarify why string.h and stdlib.h to the MPU6050 class, and math.h to the BMP180 class, both under the Arduino folder? If the need for those files is specific to the RasPi implementation, can those `#include`'s be left in the RasPi I2Cdev.h file? Or if they are specific to the RasPi examples along, can they be left in the example .c files?

**Comment by hamish2014** [comment]
Hi jrowberg,

Let me begin by stating that i am not a c++ programmer.
So hopefully you can help me out here.

The string.h, stdlib.h and math.h are required for gcc to compile the MPU6050 and BMP180 libraries, i.e. when compiling the libraries on a RaspberryPi.
Is there a c++ way of saying only include these lines (only execute these lines) if running on a RaspberryPi, perhaps i can use the gcc preproser in some manner?

I research the issue further tomorrow, when i have some time ...

**Comment by hamish2014** [comment]
Would this approach work?

1. Adding to the line to Rasbperry Pi main C++ file
  #define __RASPBERRYPI__
2. Then in the MPU6050 or BMP180 libraries 
 #ifdef __RASPBERRYPI__  #include <math.h> #endif

**Comment by hamish2014** [comment]
Hi again  jrowberg,

The approach you recommended of moving the includes to raspberry pi's i2cdev.h works.
So i am going to do that.

Thanks

**Pull request merged**
