### PR TITLE
Initial support for STM32 HAL Drivers (successor of standard peripheral library)

### PR DESCRIPTION
**Pull request by anvol**
Hi

Just finished testing i2cdevlib port to stm32. And of course I want to share my work with community)
I'm gonna port all sensors of GY-87 board and ADXL345. That's all sensors I have for now.
Proof image)
imag0201

### CODE REVIEW

**Comment by udawat** [comment]
This is a commendable effort to port this repo to STM32F4.
Does the STM HAL support means it is compatible with the whole family of STM32 microcontrollers, like F3, L0, L1, etc. ?

After going through the files, i found that the README.md file has an example code for BMP085. For a first time user, it would be great if there is an example code with main.c file for these sensors.

Can you include the project files for the IDE that you have used (if any), like Keil MDK or IAR EWARM?
This could become a good starting point for a newbie to check the sensor on their discovery boards and get an overall idea about how to use the libraries. STM32 development is quite tricky with all its Project settings and other quirks.

**Comment by sameenashaikh29** [comment]
Hi,
I am working on spi protocal on stm32f429 discovery board. Could you help me with this. I am trying to sense values from adxl345 accelerometer through spi. 
Thank You

**Comment by jrowberg** [comment]
There is clearly a ton of effort put into this core and peripheral driver set, but I'm unfamiliar with STM32. There are some conflicts now though, oddly not in any core files but in the MPU6050 drivers. Does anyone have any interest in resolving them so that this PR (or something similar) can be merged?

**Comment by eadf** [comment]
As I understand it, this HAL implementation is a different beast compared to the existing STM32 Keil MDK Pack implementation. We could merge it, but it would have to be under a different folder.

**Comment by jrowberg** [comment]
> We could merge it, but it would have to be under a different folder.

Can this existing PR be merged manually while renaming `STM32` to `STM32HAL` or similar?

**Comment by eadf** [comment]
I think you could do it in three steps:
1 "git mv" existing STM32 to STM32MDK, and make a copy of it as STM32
2 merge this PR into the copy, (make sure the result is identical to https://github.com/anvol/i2cdevlib/tree/master )
3 rename STM32 to STM32HAL and place back STM32MDK as STM32 to avoid incompatibilities.

The end result should be a STM32 containing current MDK code, with revisions history mostly intact, and this new STM32HAL as it was when anvol made the PR.
That's just a suggestion though

**Comment by jrowberg** [comment]
I like it. I'll go ahead with that approach.

**Pull request merged**
