### PR TITLE
Create I2Cdev.h

### PR DESCRIPTION
**Pull request by Anirban721260**
Is it alright ?

### CODE REVIEW

**Comment by jrowberg** [comment]
I'm not sure what the purpose of this PR is; what problem is it trying to solve, or what feature is it trying to add? It looks like a simple copy of the existing I2Cdev.h from elsewhere in the folder tree.

**Comment by Anirban721260** [comment]
Basically we robot maker extremely need I2Cdev.h library .So please fix
this issue as fast as possible.

**Comment by jrowberg** [comment]
But I have no idea what issue you are trying to fix. When installed correctly, the existing code compiles and runs as-is in typical Arduino/compatible board configurations.

**Comment by carycode** [comment]
This "I2Cdev.h" appears to be a copy of https://github.com/jrowberg/i2cdevlib/blob/master/Arduino/I2Cdev/I2Cdev.h that already exists in this repository.
The first difference I see is that the header specifying "Copyright (c) 2011 Jeff Rowberg" and the license has been cut off.

So no, it is never alright to copy someone else's work, cut off the author's signature, and pass it off as your own.
Assuming that was an accident,
is there anything else about this file that is better than the I2Cdev.h already in this repository?

**Comment by jrowberg** [comment]
Closing this PR, since even if there is a valid problem to solve, this isn't way to solve it. If further discussion is required, consider using the Ideas or Q&A section of the repository's new [Discussions](https://github.com/jrowberg/i2cdevlib/discussions) section.

**Pull request closed without merging**
