### PR TITLE
Raspberry Pi Pico port

### PR DESCRIPTION
**Pull request by meneraing**
I have included 2 examples, one for calibration and one for using the DMP. The calibration one doesn't use the functions from MPU6050.h because before even trying to port the I2Cdev library I've had already implemented that script. Results are satisfactory for me, but if needed; the ```CalibrateAccel()``` and ```CalibrateGyro()``` functions work perfectly.

Something I should do later is to review the code and remove any references for ```bool useProgMem``` because I suppose they are only used when loading data to flash memory on Arduino devices.

### CODE REVIEW

**Comment by eadf** [comment]
I just took a quick look: Some of the .vscode files contains absolute paths to your local env. 
e.g "`compilerPath": "/usr/bin/arm-none-eabi-gcc",`

Could you check if the .vscode file(s) really needs to be in this repository at all.
If they must be included: check if it possible to replace the hardcoded paths with variables.

**Comment by meneraing** [comment]
I agree with you, it will be better to just remove anything related to VS Code, after all it is just C/C++ and can be edited with any text editor. I will also change the calibration example for one that actually uses the library, since the one previously uploaded doesn't rely on I2Cdev nor MPU6050.h, becoming unrelated to the repository.

**Comment by jrowberg** [comment]
I'm okay with the updated changelog, and the rest of the contribution. Almost every one of the previous changelog comment set concerned various tweaks and additions to Arduino-specific I2C stuff, which doesn't apply on the RP2040.

**Comment by meneraing** [comment]
I've removed most of the contents from the changelog because as Jeff said, it was related to Arduino-specific I2C stuff. In any case, feel free to modify it as you see fit, no problems on my end

**Pull request merged**
